package connectFour;
/**
 * AIPlayerInterface.java
 *
 * File generated from the ConnectFour::AIPlayerInterface uml Interface
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 23/04/10 15.19.33 (23 aprile 2010) $
 */




/**
 * Description of the interface AIPlayerInterface.
 *
 */

public  interface AIPlayerInterface 
{

    /**
     *  calcolo della prossima mossa
     * @param gameState stato attuale del gioco
     * @return nuovo stato del gioco
     */
    public GameState nextMove(GameState gameState);

    /**
     * @return  il numero di nodi esaminati nel calcolo dell'ultima mossa effettuata
     */
    public Integer getExaminatedNodeNumber();

}