package connectFour;
/**
 * Heuristic.java
 *
 * File generated from the ConnectFour::Heuristic uml Class
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 23/04/10 15.19.33 (23 aprile 2010) $
 */




// Start of user code to add imports for Heuristic
 
// End of user code

/**
 * Description of the class Heuristic.
 *
 */

public class Heuristic {
		
		// Start of user code to add fields for Heuristic
		 
		// End of user code
		
		
		/**
		 * Constructor.
		 */
		public Heuristic() {
			// Start of user code for constructor Heuristic
			super();
			// End of user code
		}
		
		public Integer heuristic(GameState gameState){
                    return 0;
                }
		
		// Start of user code to add methods for Heuristic
		
		// End of user code
}