package connectFour;
/**
 * Heuristic.java
 *
 * File generated from the ConnectFour::Heuristic uml Class
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 23/04/10 15.19.33 (23 aprile 2010) $
 */

/**
 * Description of the class Heuristic.
 * classe che fornisce l'euristica con cui valutare gli stati non terminali
 */

public class Heuristic {

    /**
     * Constructor.
     */
    public Heuristic() {
            // Start of user code for constructor Heuristic
            super();
            // End of user code
    }

    /**
     * metodo che valuta la funzione euristica sullo stato passato come argomento
     * @param gameState stato di cui si vuole valutare l'euristica
     * @return il valore della funzione euristica
     */
    public Integer calculateHeuristic(GameState gameState){
        //gameState.toString();
        return 0;
    }

}